#!/usr/bin/env bash
# Bash script that transfer a file from our client to a server
size="$#";
echo "$size";
if [ $size -lt 3 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  echo "$1 $2 $3"
  scp -i "$4" "$1" "$3"@"$2":~/
fi
