#!/usr/bin/env bash
# Bash script to install Nginx
sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
