#!/usr/bin/env bash
# bash scripts to display information about subdomains

domain()
{
  ANSWER=$(dig "$1" | grep -A1 'ANSWER SECTION:' | tail -n 1)

  subdomain=$(echo "$ANSWER" | awk '{print $1;}' FS=.)
  record_type=$(echo "$ANSWER" | awk '{print $4}')
  point_to=$(echo "$ANSWER" | awk '{print $5}')

  echo "The subdomain is $subdomain is a $record_type record and points to $point_to"
}

domain "www.""$1"
domain "lb-01.""$1"
domain "web-01.""$1"
domain "web-02.""$1"
