#!/usr/bin/env bash
# displays content of a file

file="/etc/passwd"

while IFS=: read -r username password user_id group_id user_id_info home_dir command_sh
do 
  echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $command_sh. $user_id's is protected by the passcode $password, more info about the user here: $user_id_info"
done < "$file"
