#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes

hour=1
min=1

while [ $hour -le 12 ]
  do
    echo "Hour: $hour"
    while [ $min -le 59 ]
      do
        echo "$min"
        min=$((min + 1))
    done
    hour=$((hour + 1))
    min=1
done
